### ISSUE TITLE
Can not connect to any domain

### ISSUE THREAD

**Issue by javadvb** [adoconnection/EmailValidator.NET#1]
HI Dear.

I could not connect to any domain by this source code, Even gmail.

Please help me to use this source code.

best regard

**Comment by adoconnection** [comment]
for me this works fine:
```
EmailValidationResult result;

if (!emailValidator.Validate("adoconnection@gmail.com", out result))
{
    Assert.Fail("Unable to test " + email);
}

Assert.AreEqual(EmailValidationResult.OK, result, email);
```

can you take entire emailvalidator source code and run it?
